"""schemas and types only, no logic, no I/O

Layer 0 of `system_rearchitecture.md` §4.1. Replaces `the dataclasses currently
declared inside score.py`.

Rearchitecture phase 1 declares the operations contracts here: jobs, stages,
attempts, checkpoints and artifacts (``jobs``), and the failure, progress and
resource envelopes (``operations``). Phase 2 adds the data boundary: table
definitions, immutable object/fragment/snapshot handles, bounded query
commands, event/chain/dependency contracts, and import/compatibility
contracts (``data``). Frozen dataclasses and closed vocabularies only — the
strict decoder is ``engine.v2.foundation.typed``.
"""
from __future__ import annotations

from engine.v2.contracts.data import (
    CHAIN_MEMBER_V1,
    CHAIN_QUERY_V1,
    CHAIN_SNAPSHOT_V1,
    COLUMN_CONTRACT_V1,
    CONTRACT_ID_V1,
    DATA_FAILURE_CODES,
    DATA_QUERY_V1,
    DATASET_MANIFEST_V1,
    DATASET_VERSION_REF_V1,
    DEPENDENCY_PLAN_V1,
    EARNINGS_EVENT_V1,
    EVENT_REF_V1,
    FRAGMENT_RECORD_V1,
    FRAGMENT_REF_V1,
    KEY_PREDICATE_V1,
    LEGACY_MATERIALIZATION_REQUEST_V1,
    OBJECT_REF_V1,
    SNAPSHOT_IMPORT_RECEIPT_V1,
    SNAPSHOT_IMPORT_REQUEST_V1,
    SNAPSHOT_REF_V1,
    TABLE_CONTRACT_REF_V1,
    TABLE_CONTRACT_V1,
    TIME_INTERVAL_V1,
    ChainMember,
    ChainQuery,
    ChainSnapshot,
    ColumnContract,
    ContractId,
    DataQuery,
    DatasetManifest,
    DatasetVersionRef,
    DependencyEntry,
    DependencyPlan,
    EarningsEvent,
    EventRef,
    FragmentRecord,
    FragmentRef,
    KeyPredicate,
    KnowledgeMode,
    LegacyMaterializationRequest,
    ObjectRef,
    SnapshotImportReceipt,
    SnapshotImportRequest,
    SnapshotRef,
    TableContract,
    TableContractRef,
    TimeInterval,
)
from engine.v2.contracts.jobs import (
    ARTIFACT_REF_V1,
    ATTEMPT_RECEIPT_V1,
    CANCELLATION_RECEIPT_V1,
    CHECKPOINT_RECEIPT_V1,
    JOB_RECEIPT_V1,
    JOB_SPEC_V1,
    LEGACY_INPUT_MANIFEST_V1,
    STAGE_RESULT_V1,
    STAGE_SPEC_V1,
    SUBMIT_REQUEST_V1,
    ArtifactRef,
    AttemptReceipt,
    AttemptState,
    CancellationReceipt,
    CheckpointCandidate,
    CheckpointReceipt,
    EffectClass,
    JobReceipt,
    JobSpec,
    JobState,
    LegacyFileRef,
    LegacyInputManifest,
    OutputCandidate,
    ProcessState,
    StageResult,
    StageSpec,
    SubmitRequest,
)
from engine.v2.contracts.operations import (
    CAPACITY_SAMPLE_V1,
    FAILURE_CODES,
    PROBLEM_V1,
    PROGRESS_EVENT_V1,
    RESOLVED_RESOURCES_V1,
    RESOURCE_POLICY_V1,
    CapacitySample,
    Containment,
    ExecutorMode,
    LiveWindow,
    Problem,
    ProblemCategory,
    ProcessIdentity,
    ProgressEvent,
    ProgressKind,
    QueueReason,
    ResolvedResources,
    ResourcePolicy,
    ResourceProfile,
)

__all__ = [
    "ARTIFACT_REF_V1", "ATTEMPT_RECEIPT_V1", "CANCELLATION_RECEIPT_V1",
    "CAPACITY_SAMPLE_V1", "CHAIN_MEMBER_V1", "CHAIN_QUERY_V1", "CHAIN_SNAPSHOT_V1",
    "CHECKPOINT_RECEIPT_V1", "COLUMN_CONTRACT_V1", "CONTRACT_ID_V1",
    "DATA_FAILURE_CODES", "DATA_QUERY_V1", "DATASET_MANIFEST_V1",
    "DATASET_VERSION_REF_V1", "DEPENDENCY_PLAN_V1", "EARNINGS_EVENT_V1",
    "EVENT_REF_V1", "FAILURE_CODES", "FRAGMENT_RECORD_V1", "FRAGMENT_REF_V1",
    "JOB_RECEIPT_V1", "JOB_SPEC_V1", "KEY_PREDICATE_V1",
    "LEGACY_INPUT_MANIFEST_V1", "LEGACY_MATERIALIZATION_REQUEST_V1",
    "OBJECT_REF_V1", "PROBLEM_V1", "PROGRESS_EVENT_V1",
    "RESOLVED_RESOURCES_V1", "RESOURCE_POLICY_V1",
    "SNAPSHOT_IMPORT_RECEIPT_V1", "SNAPSHOT_IMPORT_REQUEST_V1", "SNAPSHOT_REF_V1",
    "STAGE_RESULT_V1", "STAGE_SPEC_V1", "SUBMIT_REQUEST_V1",
    "TABLE_CONTRACT_REF_V1", "TABLE_CONTRACT_V1", "TIME_INTERVAL_V1",
    "ArtifactRef", "AttemptReceipt", "AttemptState", "CancellationReceipt",
    "CapacitySample", "ChainMember", "ChainQuery", "ChainSnapshot",
    "CheckpointCandidate", "CheckpointReceipt", "ColumnContract", "Containment",
    "ContractId", "DataQuery", "DatasetManifest", "DatasetVersionRef",
    "DependencyEntry", "DependencyPlan", "EarningsEvent", "EffectClass",
    "EventRef", "ExecutorMode", "FragmentRecord", "FragmentRef", "JobReceipt",
    "JobSpec", "JobState", "KeyPredicate", "KnowledgeMode", "LegacyFileRef",
    "LegacyInputManifest", "LegacyMaterializationRequest", "LiveWindow",
    "ObjectRef", "OutputCandidate", "Problem", "ProblemCategory",
    "ProcessIdentity", "ProcessState", "ProgressEvent", "ProgressKind",
    "QueueReason", "ResolvedResources", "ResourcePolicy", "ResourceProfile",
    "SnapshotImportReceipt", "SnapshotImportRequest", "SnapshotRef",
    "StageResult", "StageSpec", "SubmitRequest", "TableContract",
    "TableContractRef", "TimeInterval",
]
