"""Frozen model contracts, verified loading, and read-only inference."""

from .adapters import (
    AdapterError,
    InferenceAdapter,
    JoblibEstimatorAdapter,
    JsonLinearAdapter,
    RuntimeFitForbidden,
    default_adapters,
)
from .contracts import (
    MODEL_NOT_READY,
    MODEL_READY,
    ArtifactMember,
    InferenceRequest,
    InferenceResult,
    ModelBinding,
    ModelRelease,
    PredictionFrame,
)
from .inventory import (
    DEPLOYMENT_ID,
    FEATURE_ROLES,
    KNOWN_CLOCK_IDS,
    NON_MODEL_STATE_ITEMS,
    RELEASE_ID,
    FoldCoverageEntry,
    NonModelStateEntry,
    current_release_inventory,
    non_model_state_inventory,
    registry_drift_issues,
    served_roles,
    tier4_fold_coverage,
)
from .loader import FrozenInference
from .releases import (
    ARTIFACT_INVENTORY_MEMBER_V1,
    MODEL_ARTIFACT_INVENTORY_V1,
    MODEL_RELEASE_REFUSAL,
    MODEL_RELEASE_V1,
    RELEASE_BINDING_V1,
    RELEASE_REQUIREMENT_V1,
    ArtifactInventoryMember,
    ModelArtifactInventory,
    ModelReleaseInventory,
    ModelReleaseRefusal,
    ReleaseBinding,
    ReleaseIssue,
    ReleaseRequirement,
    release_issues,
    require_complete_release,
)

__all__ = [
    "ARTIFACT_INVENTORY_MEMBER_V1",
    "AdapterError",
    "ArtifactInventoryMember",
    "ArtifactMember",
    "DEPLOYMENT_ID",
    "FEATURE_ROLES",
    "FoldCoverageEntry",
    "FrozenInference",
    "InferenceAdapter",
    "InferenceRequest",
    "InferenceResult",
    "JoblibEstimatorAdapter",
    "JsonLinearAdapter",
    "KNOWN_CLOCK_IDS",
    "MODEL_ARTIFACT_INVENTORY_V1",
    "MODEL_NOT_READY",
    "MODEL_READY",
    "MODEL_RELEASE_REFUSAL",
    "MODEL_RELEASE_V1",
    "ModelArtifactInventory",
    "ModelBinding",
    "ModelRelease",
    "ModelReleaseInventory",
    "ModelReleaseRefusal",
    "NON_MODEL_STATE_ITEMS",
    "NonModelStateEntry",
    "PredictionFrame",
    "RELEASE_BINDING_V1",
    "RELEASE_ID",
    "RELEASE_REQUIREMENT_V1",
    "ReleaseBinding",
    "ReleaseIssue",
    "ReleaseRequirement",
    "RuntimeFitForbidden",
    "current_release_inventory",
    "default_adapters",
    "non_model_state_inventory",
    "registry_drift_issues",
    "release_issues",
    "require_complete_release",
    "served_roles",
    "tier4_fold_coverage",
]
