#!/usr/bin/env python3
"""P6-1: generate the Phase 6 capability matrix and adapter/read-set inventory.

Two halves, kept apart on purpose:

* **Discovery** reads the actual source with :mod:`ast` and regular
  expressions — never an import of ``engine.*``, so nothing loads a panel.
  It finds every consumer entrypoint: the legacy FastAPI routes, the v2
  API and operations-server routes, the legacy SPA views and controls, the
  React routes, every ``__main__`` CLI and argparse subcommand, the legacy
  nightly steps, the v2 nightly DAG stages, the supervised legacy actions,
  the coordinator effects, and the legacy ledger/report/export/backup
  writers. It also finds every v2 -> legacy adapter edge: the exact-symbol
  ledger ``checks/legacy_adapters.json`` plus the file-format adapter
  modules.
* **Declarations** (``tools/phase6_capabilities.toml``) carry the judgement
  a parser cannot make: which capability an entrypoint belongs to, its
  disposition and owning phase. The generated matrix joins the two and
  records, per row, whether each claimed new entrypoint and test resolves.

``checks/phase6_inventory.py`` turns the joined document into findings.
This tool only reports; it always exits 0 unless its inputs cannot be read.

Usage::

    python3 tools/phase6_inventory.py                       # summary only
    python3 tools/phase6_inventory.py --out /tmp/p6.json    # full document
    python3 tools/phase6_inventory.py --write-guide         # refresh the guide section

No data value is read: only source files, file names and the declarations.
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SCHEMA_VERSION = "phase6_capability_matrix.v1.0"
DECLARATIONS = Path("tools/phase6_capabilities.toml")
GUIDE = Path("guides/rearchitecture_phase6_consumer_parity.md")
ADAPTER_LEDGER = Path("checks/legacy_adapters.json")
GUIDE_BEGIN = "<!-- phase6-inventory:begin (generated by tools/phase6_inventory.py --write-guide; do not edit) -->"
GUIDE_END = "<!-- phase6-inventory:end -->"

DISPOSITIONS = ("native", "compatibility-adapter", "CLI-with-user-acceptance-needed",
                "missing", "dormant-historical")
#: Owners a capability row may name (brief: P6-2..P6-6, 8A, post-cutover).
ROW_OWNERS = ("P6-2", "P6-3", "P6-4", "P6-5", "P6-6", "8A", "post-cutover")
#: Owners an adapter edge may name: its consumer/removal phase. Earlier
#: phases that are still open own the edges their own migration removes.
EDGE_OWNERS = ("P3B", "P4", "P5") + ROW_OWNERS
#: The required inventory entries of the Phase 6 guide, one key each.
REQUIRED_AREAS = {
    "nightly": "nightly refresh/score/selfcheck/publish/backup",
    "decisions": "predictions and settlement",
    "books": "hypothetical/contrarian books and funding",
    "research": "replay/research and generated reports",
    "board": "board filters/deep links",
    "strategy": "strategy/refusal details",
    "models": "model evidence",
    "history": "history/analogs",
    "operations": "flags/finality/health/quotas",
    "export": "phone/offline export",
}
#: Dispositions whose ``new`` entrypoints must resolve to real source.
RESOLVING = frozenset({"native", "compatibility-adapter", "CLI-with-user-acceptance-needed"})

#: Source files each discovery reads. Paths, not globs, so a moved file is
#: a loud KeyError/FileNotFoundError rather than a silently empty set.
LEGACY_APP = "dashboard/earnings_app.py"
V2_API = "engine/v2/serving/api.py"
V2_OPS_SERVER = "engine/v2/serving/operations.py"
LEGACY_SPA = "engine/dashboard/static/assets/app.js"
LEGACY_HTML = "engine/dashboard/static/index.html"
REACT_ROUTES = "ui/src/routes.ts"
LEGACY_NIGHTLY = "engine/dashboard/nightly.py"
V2_NIGHTLY = "engine/v2/ops/nightly.py"
V2_ACTIONS = "engine/v2/ops/legacy_adapter.py"
V2_EFFECTS = "engine/v2/ops/effects_graph.py"
V2_STAGES = "engine/v2/ops/stages.py"
SUBCOMMAND_CLIS = {"engine/ledger.py": "engine.ledger", "engine/v2/ops/cli.py": "ops"}
CLI_ROOTS = ("engine", "dashboard", "tools")
EXPERIMENT_GLOB = "experiments/*/run.py"
WRITER_MODULES = ("engine/ledger.py", "engine/portfolio.py", "engine/report.py", "engine/evaluate.py",
                  "engine/dashboard/render.py", "engine/dashboard/publish.py",
                  "engine/dashboard/model_evidence.py", "engine/dashboard/selfcheck.py",
                  "tools/private_mirror.py")
_WRITE_CALLS = frozenset({"write_text", "write_bytes", "to_csv", "to_parquet", "savefig", "dump",
                          "write", "writelines", "copy2", "copytree", "copyfile", "symlink"})
#: v2 modules that adapt a legacy file format without importing ``engine.*``
#: are found by name; the exact-symbol ledger finds the importing ones.
_ADAPTER_NAME = re.compile(r"legacy|compat|bridge|adapter")


# ---------------------------------------------------------------------------
# small source readers
# ---------------------------------------------------------------------------


def _text(root: Path, rel: str) -> str:
    return (root / rel).read_text()


def _tree(root: Path, rel: str) -> ast.Module:
    return ast.parse(_text(root, rel), filename=rel)


def _const_strings(node: ast.AST) -> list[str]:
    if isinstance(node, (ast.Tuple, ast.List, ast.Set)):
        return [e.value for e in node.elts if isinstance(e, ast.Constant) and isinstance(e.value, str)]
    return []


def _module_assign(tree: ast.Module, name: str) -> ast.AST | None:
    for node in tree.body:
        targets = node.targets if isinstance(node, ast.Assign) else (
            [node.target] if isinstance(node, ast.AnnAssign) else [])
        if any(isinstance(t, ast.Name) and t.id == name for t in targets):
            return node.value
    return None


def _add(found: dict, ident: str, kind: str, source: str) -> None:
    found.setdefault(ident, {"kind": kind, "source": source})


# ---------------------------------------------------------------------------
# discovery: routes and views
# ---------------------------------------------------------------------------


def _fastapi_routes(root: Path, rel: str, app: str, found: dict) -> None:
    for node in ast.walk(_tree(root, rel)):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.args:
            method = node.func.attr
            first = node.args[0]
            if not (isinstance(first, ast.Constant) and isinstance(first.value, str)):
                continue
            if method in ("get", "post", "put", "delete", "patch") and first.value.startswith("/"):
                _add(found, f"route:{app} {method.upper()} {first.value}", "route", rel)
            elif method == "mount":
                _add(found, f"route:{app} MOUNT {first.value}", "route", rel)


def _handler_routes(root: Path, rel: str, app: str, found: dict) -> None:
    """``path == "/x"`` / ``path.startswith("/x")`` / ``... in _VIEWS`` in a
    ``BaseHTTPRequestHandler.do_GET``."""
    tree = _tree(root, rel)
    views = _const_strings(_module_assign(tree, "_VIEWS"))
    for cls in (n for n in tree.body if isinstance(n, ast.ClassDef)):
        for fn in (m for m in cls.body if isinstance(m, ast.FunctionDef) and m.name.startswith("do_")):
            verb = fn.name[3:]
            for node in ast.walk(fn):
                if isinstance(node, ast.Compare) and isinstance(node.ops[0], ast.Eq):
                    for value in _const_strings(ast.Tuple(elts=node.comparators)):
                        if value.startswith("/"):
                            _add(found, f"route:{app} {verb} {value}", "route", rel)
                if isinstance(node, ast.Compare) and isinstance(node.ops[0], ast.In):
                    if any(isinstance(c, ast.Name) and c.id == "_VIEWS" for c in node.comparators):
                        for view in views:
                            _add(found, f"route:{app} {verb} /{view}", "route", rel)
                if (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                        and node.func.attr == "startswith" and node.args
                        and isinstance(node.args[0], ast.Constant)):
                    _add(found, f"route:{app} {verb} {node.args[0].value}*", "route", rel)


def _route_pairs(node: ast.AST, views: list[str]) -> list[tuple[str, str]]:
    """The ``(method, path)`` pairs one route-table entry declares."""
    if isinstance(node, ast.Starred):
        return _starred_views(node.value, views)
    if not isinstance(node, ast.Tuple) or len(node.elts) < 2:
        return []
    values = _const_strings(ast.Tuple(elts=list(node.elts[:2])))
    return [(values[0], values[1])] if len(values) == 2 else []


def _starred_views(node: ast.AST, views: list[str]) -> list[tuple[str, str]]:
    """``*(("GET", f"/{view}") for view in _VIEWS if view != "derivation")``.

    Expands to one static route per view, honouring the generator's own
    ``!=`` exclusions (a view declared separately stays only once).
    """
    if not isinstance(node, ast.GeneratorExp) or not views:
        return []
    elt = node.elt
    if not (isinstance(elt, ast.Tuple) and len(elt.elts) == 2):
        return []
    method, path = elt.elts
    if not (isinstance(method, ast.Constant) and method.value == "GET"):
        return []
    if not (isinstance(path, ast.JoinedStr) and path.values
            and isinstance(path.values[0], ast.Constant) and path.values[0].value == "/"):
        return []
    excluded = {test.comparators[0].value for gen in node.generators for test in gen.ifs
                if isinstance(test, ast.Compare) and isinstance(test.ops[0], ast.NotEq)
                and isinstance(test.comparators[0], ast.Constant)}
    return [("GET", f"/{view}") for view in views if view not in excluded]


def _declared_routes(root: Path, rel: str, app: str, found: dict) -> None:
    """The module-level ``STATIC_ROUTES``/``PARAMETERIZED_ROUTES`` tuples.

    The same declarative table the route probe imports; a parameterized prefix
    is recorded as ``<prefix>*``, matching the ``startswith`` id form.
    """
    tree = _tree(root, rel)
    views = _const_strings(_module_assign(tree, "_VIEWS"))
    for name, parameterized in (("STATIC_ROUTES", False), ("PARAMETERIZED_ROUTES", True)):
        node = _module_assign(tree, name)
        if not isinstance(node, ast.Tuple):
            continue
        for entry in node.elts:
            for method, path in _route_pairs(entry, views):
                suffix = "*" if parameterized else ""
                _add(found, f"route:{app} {method} {path}{suffix}", "route", rel)


def _spa_views(root: Path, found: dict) -> None:
    text = _text(root, LEGACY_SPA)
    match = re.search(r"const AREA_VIEWS\s*=\s*\{([^}]*)\}", text)
    for area, views in re.findall(r"(\w+):\s*\[([^\]]*)\]", match.group(1) if match else ""):
        for view in re.findall(r'"([\w-]+)"', views):
            _add(found, f"view:legacy #/{area}/{view}", "view", LEGACY_SPA)


def _spa_controls(root: Path, found: dict) -> None:
    for tag, ident in re.findall(r"<(select|input)\b[^>]*\bid=\"([\w-]+)\"", _text(root, LEGACY_HTML)):
        _add(found, f"control:legacy {ident}", "control", LEGACY_HTML)


def _react_routes(root: Path, found: dict) -> None:
    for name in re.findall(r'\{\s*name:\s*"(\w+)"', _text(root, REACT_ROUTES)):
        _add(found, f"view:ui #{name}", "view", REACT_ROUTES)


# ---------------------------------------------------------------------------
# discovery: CLIs and subcommands
# ---------------------------------------------------------------------------


def _is_main_guard(node: ast.AST) -> bool:
    return (isinstance(node, ast.If) and isinstance(node.test, ast.Compare)
            and isinstance(node.test.left, ast.Name) and node.test.left.id == "__name__")


def _main_modules(root: Path) -> list[str]:
    result = []
    for top in CLI_ROOTS:
        for path in sorted((root / top).rglob("*.py")):
            rel = path.relative_to(root).as_posix()
            if "__pycache__" in rel:
                continue
            tree = ast.parse(path.read_text(), filename=rel)
            if path.name == "__main__.py" or any(_is_main_guard(n) for n in tree.body):
                result.append(rel)
    return result


def _clis(root: Path, found: dict) -> None:
    for rel in _main_modules(root):
        _add(found, f"cli:{rel}", "cli", rel)
    runners = sorted(root.glob(EXPERIMENT_GLOB))
    if runners:
        _add(found, f"cli-family:{EXPERIMENT_GLOB}", "cli", f"{len(runners)} runners")


def _loop_values(tree: ast.AST) -> dict[int, list[str]]:
    """``for name in ("a", "b"): x.add_parser(name)`` -> {call id: [a, b]}."""
    result = {}
    for loop in (n for n in ast.walk(tree) if isinstance(n, ast.For)):
        values = _const_strings(loop.iter)
        if not (values and isinstance(loop.target, ast.Name)):
            continue
        for call in ast.walk(loop):
            if (isinstance(call, ast.Call) and isinstance(call.func, ast.Attribute)
                    and call.func.attr == "add_parser" and call.args
                    and isinstance(call.args[0], ast.Name) and call.args[0].id == loop.target.id):
                result[id(call)] = values
    return result


def _subcommands(root: Path, rel: str, prefix: str, found: dict) -> None:
    """argparse ``add_subparsers``/``add_parser`` chains, nested by variable."""
    tree = _tree(root, rel)
    looped = _loop_values(tree)
    paths: dict[str, tuple[str, ...]] = {}
    assigns = sorted((n for n in ast.walk(tree) if isinstance(n, (ast.Assign, ast.Expr))),
                     key=lambda n: (n.lineno, n.col_offset))
    for node in assigns:
        call = node.value
        if not (isinstance(call, ast.Call) and isinstance(call.func, ast.Attribute)
                and isinstance(call.func.value, ast.Name)):
            continue
        parent = paths.get(call.func.value.id, ())
        target = node.targets[0].id if isinstance(node, ast.Assign) and isinstance(
            node.targets[0], ast.Name) else None
        if call.func.attr == "add_subparsers" and target:
            paths[target] = parent
        elif call.func.attr == "add_parser":
            names = looped.get(id(call)) or _const_strings(ast.Tuple(elts=call.args[:1]))
            for name in names:
                _add(found, f"cli:{prefix} " + " ".join(parent + (name,)), "subcommand", rel)
            if target and len(names) == 1:
                paths[target] = parent + (names[0],)


# ---------------------------------------------------------------------------
# discovery: nightly steps, DAG stages, actions, effects, writers
# ---------------------------------------------------------------------------


def _legacy_nightly_steps(root: Path, found: dict) -> None:
    text = _text(root, LEGACY_NIGHTLY)
    steps = set(re.findall(r'report\.mark\("(\w+)"', text)) | set(re.findall(r'report\.steps\["(\w+)"\]', text))
    for step in sorted(steps):
        _add(found, f"nightly:legacy {step}", "nightly-step", LEGACY_NIGHTLY)


def _v2_nightly_stages(root: Path, found: dict) -> None:
    tree = _tree(root, V2_NIGHTLY)
    stages = set(_const_strings(_module_assign(tree, "_DAG_STAGES")))
    graph = _module_assign(tree, "GRAPH")
    if isinstance(graph, ast.Dict):
        stages |= {k.value for k in graph.keys if isinstance(k, ast.Constant)}
    for node in ast.walk(tree):  # ("materialize",) + stages
        if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add) and isinstance(node.left, ast.Tuple):
            if isinstance(node.right, ast.Name) and node.right.id == "stages":
                stages |= set(_const_strings(node.left))
    for stage in sorted(stages):
        _add(found, f"nightly:v2 {stage}", "dag-stage", V2_NIGHTLY)


def _functions(tree: ast.Module):
    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            yield node.name, node
        elif isinstance(node, ast.ClassDef):
            for member in node.body:
                if isinstance(member, ast.FunctionDef):
                    yield f"{node.name}.{member.name}", member


def _v2_actions_and_effects(root: Path, found: dict) -> None:
    for name, _ in _functions(_tree(root, V2_ACTIONS)):
        if name.startswith("_action_"):
            _add(found, "action:legacy_" + name.removeprefix("_action_"), "action", V2_ACTIONS)
    for name, _ in _functions(_tree(root, V2_EFFECTS)):
        if name.endswith("_effect") and not name.startswith("_"):
            _add(found, f"effect:{name}", "effect", V2_EFFECTS)


def _called_names(fn: ast.AST) -> set[str]:
    return {c.func.attr if isinstance(c.func, ast.Attribute) else getattr(c.func, "id", "")
            for c in ast.walk(fn) if isinstance(c, ast.Call)}


def writer_functions(tree: ast.Module) -> list[str]:
    """Public functions that write a file, directly or through a same-module
    helper (transitive closure), excluding ``main`` (covered as a CLI)."""
    calls = {name: _called_names(fn) for name, fn in _functions(tree)}
    short = {name.rsplit(".", 1)[-1] for name in calls}
    writers = {name for name, called in calls.items() if called & _WRITE_CALLS}
    changed = True
    while changed:
        names = {w.rsplit(".", 1)[-1] for w in writers}
        grown = {n for n, called in calls.items() if called & names & short} - writers
        writers |= grown
        changed = bool(grown)
    return sorted(w for w in writers if not any(p.startswith("_") for p in w.split("."))
                  and w != "main")


def _writers(root: Path, found: dict) -> None:
    for rel in WRITER_MODULES:
        for name in writer_functions(_tree(root, rel)):
            _add(found, f"writer:{rel}::{name}", "writer", rel)


def discover_entrypoints(root: Path = ROOT) -> dict[str, dict]:
    """Every consumer entrypoint id -> {kind, source}. Deterministic order."""
    found: dict[str, dict] = {}
    _fastapi_routes(root, LEGACY_APP, "legacy-app", found)
    _fastapi_routes(root, V2_API, "v2-api", found)
    _handler_routes(root, V2_OPS_SERVER, "v2-ops", found)
    _declared_routes(root, V2_OPS_SERVER, "v2-ops", found)
    _spa_views(root, found)
    _spa_controls(root, found)
    _react_routes(root, found)
    _clis(root, found)
    for rel, prefix in SUBCOMMAND_CLIS.items():
        _subcommands(root, rel, prefix, found)
    _legacy_nightly_steps(root, found)
    _v2_nightly_stages(root, found)
    _v2_actions_and_effects(root, found)
    _writers(root, found)
    return dict(sorted(found.items()))


# ---------------------------------------------------------------------------
# discovery: adapter edges
# ---------------------------------------------------------------------------


def _legacy_imports(tree: ast.Module) -> bool:
    for node in ast.walk(tree):
        names = [node.module or ""] if isinstance(node, ast.ImportFrom) and node.level == 0 else (
            [a.name for a in node.names] if isinstance(node, ast.Import) else [])
        if any((n == "engine" or n.startswith("engine.")) and not n.startswith("engine.v2") for n in names):
            return True
    return False


def adapter_modules(root: Path = ROOT) -> list[str]:
    """v2-side modules that touch the legacy runtime or a legacy file format:
    named ``*legacy*``/``*compat*``/``*bridge*``/``*adapter*``, or importing
    a non-v2 ``engine.*`` module, under ``engine/v2`` and ``tools/v2_*``."""
    candidates = sorted((root / "engine/v2").rglob("*.py")) + sorted((root / "tools").glob("v2_*.py"))
    result = []
    for path in candidates:
        rel = path.relative_to(root).as_posix()
        if "__pycache__" in rel:
            continue
        if _ADAPTER_NAME.search(path.name) or _legacy_imports(ast.parse(path.read_text(), filename=rel)):
            result.append(rel)
    return result


def ledger_edges(root: Path = ROOT) -> list[dict]:
    """One edge per exact-symbol entry of ``checks/legacy_adapters.json``."""
    ledger = json.loads((root / ADAPTER_LEDGER).read_text())
    return [{"id": f"edge:{a['module']}::{a['legacy_symbol']}", "module": a["module"],
             "legacy_symbol": a["legacy_symbol"], "reads": a.get("read_set", ""),
             "ledger_removal_phase": a.get("removal_phase", "")}
            for a in ledger["adapters"]]


# ---------------------------------------------------------------------------
# declarations and resolution
# ---------------------------------------------------------------------------


def load_declarations(path: Path) -> dict:
    with path.open("rb") as handle:
        return tomllib.load(handle)


def _symbols(tree: ast.Module) -> set[str]:
    names = {name for name, _ in _functions(tree)}
    names |= {n.name for n in tree.body if isinstance(n, ast.ClassDef)}
    for node in tree.body:
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            names |= {t.id for t in targets if isinstance(t, ast.Name)}
    return names


def resolve_symbol(root: Path, ref: str) -> bool:
    """``path`` or ``path::Symbol`` / ``path::Class::method`` exists in source.
    ``.py`` files are parsed; any other file is searched for the symbol text."""
    rel, _, symbol = ref.partition("::")
    path = root / rel
    if not path.is_file():
        return False
    if not symbol:
        return True
    if path.suffix == ".py":
        return symbol.replace("::", ".") in _symbols(ast.parse(path.read_text(), filename=rel))
    return re.search(rf"\b{re.escape(symbol)}\b", path.read_text()) is not None


def _job_kind_names(root: Path) -> set[str]:
    """The supervised job kinds the runtime registry actually allows.

    A ``job:<kind>`` declaration names the allowlist entry itself rather than
    a path into the tools, so it resolves against the source that owns the
    registry. For the real repository root the runtime registry is the one
    authority -- it also knows every kind built in a loop rather than a
    literal ``JobKind(...)`` call (the outbox effects, the legacy action
    family, ``incremental_refresh``). A synthetic test tree gets the AST scan
    fallback, because importing this checkout's registry would answer for the
    wrong tree; the file is absent only in synthetic trees that claim no job
    kind, which resolve to the empty set.
    """
    if root.resolve() == ROOT.resolve():
        from engine.v2.ops.stages import registry

        return set(registry().names())
    path = root / V2_STAGES
    if not path.is_file():
        return set()
    names = set()
    for node in ast.walk(ast.parse(path.read_text(), filename=V2_STAGES)):
        if (isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
                and node.func.id == "JobKind"):
            for keyword in node.keywords:
                if (keyword.arg == "name" and isinstance(keyword.value, ast.Constant)
                        and isinstance(keyword.value.value, str)):
                    names.add(keyword.value.value)
    return names


def resolve_entrypoint(root: Path, ref: str, discovered: dict) -> bool:
    if ref.startswith("py:"):
        return resolve_symbol(root, ref.removeprefix("py:"))
    if ref.startswith("job:"):
        return ref.removeprefix("job:") in _job_kind_names(root)
    return ref in discovered


def _row(root: Path, row: dict, discovered: dict) -> dict:
    new = list(row.get("new", []))
    tests = list(row.get("tests", []))
    return {
        "id": row.get("id", ""), "area": row.get("area", ""), "capability": row.get("capability", ""),
        "old": list(row.get("old", [])), "new": new,
        "new_resolved": {ref: resolve_entrypoint(root, ref, discovered) for ref in new if ref != "MISSING"},
        "producer": row.get("producer", ""), "identity": row.get("identity", ""),
        "tests": tests, "tests_resolved": {t: resolve_symbol(root, t) for t in tests},
        "disposition": row.get("disposition", ""), "owner": row.get("owner", ""),
        "active": bool(row.get("active", True)), "interactive": bool(row.get("interactive", False)),
        "decision": row.get("decision", ""), "notes": row.get("notes", ""),
    }


def _edges(root: Path, decl: dict) -> list[dict]:
    owner_map = decl.get("edge_owner_map", {})
    consumers = decl.get("edge_consumer_map", {})
    overrides = {o["id"]: o for o in decl.get("edge_override", [])}
    edges = []
    for edge in ledger_edges(root):
        override = overrides.get(edge["id"], {})
        edge.update(kind="exact-symbol",
                    owner=override.get("owner", owner_map.get(edge["ledger_removal_phase"], "")),
                    consumer=override.get("consumer", consumers.get(edge["module"], "")),
                    active=override.get("active", True), notes=override.get("notes", ""),
                    module_exists=True)
        edges.append(edge)
    for edge in decl.get("edge", []):
        edges.append({"id": edge.get("id", ""), "kind": edge.get("kind", "file-format"),
                      "module": edge.get("module", ""), "legacy_symbol": "",
                      "reads": edge.get("reads", ""), "ledger_removal_phase": "",
                      "owner": edge.get("owner", ""), "consumer": edge.get("consumer", ""),
                      "active": edge.get("active", True), "notes": edge.get("notes", ""),
                      "module_exists": resolve_symbol(root, edge.get("module", ""))})
    return edges


def build_document(root: Path = ROOT, declarations: Path | None = None,
                   discovered: dict | None = None) -> dict:
    decl = load_declarations(root / (declarations or DECLARATIONS))
    discovered = discover_entrypoints(root) if discovered is None else discovered
    rows = [_row(root, row, discovered) for row in decl.get("row", [])]
    excluded = [{"ids": list(e.get("ids", [])), "reason": e.get("reason", "")}
                for e in decl.get("excluded", [])]
    return {"schema_version": SCHEMA_VERSION, "discovered": discovered, "rows": rows,
            "excluded": excluded, "adapter_modules": adapter_modules(root),
            "adapter_edges": _edges(root, decl), "user_decisions": list(decl.get("user_decision", []))}


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------


def _cell(values) -> str:
    text = "<br>".join(f"`{v}`" for v in values) if isinstance(values, list) else str(values)
    return (text or "-").replace("|", "\\|").replace("\n", " ")


def counts(document: dict) -> dict[str, int]:
    result = {d: 0 for d in DISPOSITIONS}
    for row in document["rows"]:
        result[row["disposition"]] = result.get(row["disposition"], 0) + 1
    return result


def _tally(items, key) -> str:
    result: dict[str, int] = {}
    for item in items:
        result[item[key] or "UNOWNED"] = result.get(item[key] or "UNOWNED", 0) + 1
    return ", ".join(f"{k} {v}" for k, v in sorted(result.items()))


def _matrix_lines(document: dict) -> list[str]:
    lines = ["| Row | Capability | Old entrypoint | New v2 entrypoint | Producer | Snapshot/release identity "
             "| Tests | Disposition | Owner |", "|---|---|---|---|---|---|---|---|---|"]
    for area in REQUIRED_AREAS:
        for row in (r for r in document["rows"] if r["area"] == area):
            status = row["disposition"] + ("" if row["active"] else " (dormant reader)")
            lines.append("| " + " | ".join([
                f"`{row['id']}`", _cell(row["capability"]), _cell(row["old"]), _cell(row["new"]),
                _cell(row["producer"]), _cell(row["identity"]), _cell(row["tests"]), status,
                row["owner"]]) + " |")
    return lines


def _missing_lines(document: dict) -> list[str]:
    lines = ["| Row | Missing capability | Owner | What is missing |", "|---|---|---|---|"]
    for row in document["rows"]:
        if row["disposition"] == "missing" or "MISSING" in row["new"]:
            lines.append(f"| `{row['id']}` | {_cell(row['capability'])} | {row['owner']} | {_cell(row['notes'])} |")
    return lines


def _edge_lines(document: dict) -> list[str]:
    lines = ["| Edge | Kind | Reads | Consumer | Owner (removal) | Ledger label |", "|---|---|---|---|---|---|"]
    for edge in document["adapter_edges"]:
        lines.append(f"| `{edge['id'].removeprefix('edge:')}` | {edge['kind']} | {_cell(edge['reads'])} | "
                     f"{_cell(edge['consumer'])} | {edge['owner'] or 'UNOWNED'} | "
                     f"{_cell(edge['ledger_removal_phase'])} |")
    return lines


def render_markdown(document: dict) -> str:
    tally = counts(document)
    lines = [GUIDE_BEGIN, "", f"Schema `{SCHEMA_VERSION}`: {len(document['discovered'])} discovered "
             f"entrypoints, {len(document['rows'])} capability rows, "
             f"{sum(len(e['ids']) for e in document['excluded'])} excluded tooling entrypoints, "
             f"{len(document['adapter_edges'])} adapter edges.", "",
             "Rows per disposition: " + ", ".join(f"{k} {v}" for k, v in tally.items()) + ".", "",
             "Rows per owner: " + _tally(document["rows"], "owner") + ".", "",
             "Adapter edges per owner: " + _tally(document["adapter_edges"], "owner") + ".",
             "", "#### Capability matrix", ""]
    lines += _matrix_lines(document)
    lines += ["", "#### MISSING capabilities (the P6-2..P6-5 work)", ""] + _missing_lines(document)
    lines += ["", "#### Needs a user decision", ""]
    lines += [f"- **{d['id']}** ({_cell(d['rows'])}): {d['question']}"
              for d in document["user_decisions"]] or ["- none"]
    lines += ["", "#### Excluded entrypoints (migration and verification tooling, not consumers)", ""]
    lines += [f"- {_cell(e['ids'])}: {e['reason']}" for e in document["excluded"]]
    lines += ["", "#### Active adapter and read-set inventory", ""] + _edge_lines(document)
    lines += ["", GUIDE_END]
    return "\n".join(lines) + "\n"


def guide_block(text: str) -> str | None:
    start, end = text.find(GUIDE_BEGIN), text.find(GUIDE_END)
    if start < 0 or end < start:
        return None
    return text[start:end + len(GUIDE_END)] + "\n"


def write_guide(root: Path, markdown: str) -> None:
    path = root / GUIDE
    text = path.read_text()
    current = guide_block(text)
    if current is None:
        raise SystemExit(f"{GUIDE}: no generated-section marker; add the section first")
    path.write_text(text.replace(current, markdown))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--declarations", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=None, help="write the full JSON document here")
    parser.add_argument("--write-guide", action="store_true", help="refresh the generated guide section")
    args = parser.parse_args(argv)
    document = build_document(args.root, args.declarations)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(document, indent=2) + "\n")
    if args.write_guide:
        write_guide(args.root, render_markdown(document))
    print(f"discovered {len(document['discovered'])} entrypoints; {len(document['rows'])} rows; "
          f"{len(document['adapter_edges'])} adapter edges")
    print("dispositions: " + ", ".join(f"{k}={v}" for k, v in counts(document).items()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
